#!/usr/bin/env python3
#
# EPITECH PROJECT, 2020
# 201yams_2019
# File description:
# 201yams
#

import sys
import math

def check_for_err():
    halp = open("help", "r")

    if len(sys.argv) > 1 and sys.argv[1] == "-h":
        print(halp.read())
        sys.exit(0)
    if len(sys.argv) != 3:
        print("Flag error. Try -h for more informations.")
        sys.exit(84)
    flag = []
    for i in range(1, len(sys.argv)):
        try:
            flag.append(int(sys.argv[i]))
        except ValueError:
            print("Flag error. Try -h for more informations.")
            sys.exit(84)
        if flag[i - 1] < 50 :
            print("Flag error. Try -h for more informations.")
            sys.exit(84)
    return flag

def law_xy(val):
    tab = [6 * [0] for i in  range(6)]

    for i in range(len(tab) - 1):
        for j in range(len(tab[i]) - 1):
            x = (j + 1) * 10
            y = (i + 1) * 10
            tab[i][j] = ((val[0] - x)*(val[1] - y)) / ((5*val[0] - 150)*(5*val[1] - 150))
        tab[i][5] = sum(tab[i])
    for i in range(len(tab[0])):
        for j in range(len(tab) - 1):
            tab[5][i] += tab[j][i]
    for i in range(len(tab)):
        for j in range(len(tab[i])):
            tab[i][j] = round(tab[i][j], 3)
    return tab

def law_z():
    return tab

def calc(val):
    tab_xy = law_xy(val)
    print(tab_xy)
    return 0

def main():
    x = check_for_err()
    print(x)
    calc(x)

if __name__ == "__main__":
    main()
